---
- name: Ensure apt cache is up to date
  apt:
    update_cache: true

- name: Add Custom Host
  import_tasks: ../common/tasks/hosts.yml
  when: add_custom_host | default(false)

- name: Install Docker
  import_tasks: ../common/tasks/docker_install.yml
  when: install_docker | default(false)

- name: Ensure compose project directory exists
  file:
    path: "{{ docker_compose_project_dir }}"
    state: directory
    mode: "0755"

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_project_dir }}/docker-compose.yml"
    mode: "0644"

- name: Stop existing containers (if any)
  command: docker compose down
  args:
    chdir: "{{ docker_compose_project_dir }}"
  ignore_errors: true

- name: Start Docker Compose stack
  command: docker compose up -d
  args:
    chdir: "{{ docker_compose_project_dir }}"

- name: Wait for PostgreSQL to be ready
  wait_for:
    host: "{{ ansible_host }}"
    port: 5432
    timeout: 60
    delay: 10

- name: Wait for pgAdmin to be ready
  wait_for:
    host: "{{ ansible_host }}"
    port: 5050
    timeout: 60
    delay: 15
