---
- name: Restart nginx container
  command: docker compose restart nginx
  args:
    chdir: "{{ docker_compose_project_dir }}"
  async: 60
  poll: 5

- name: Restart docker-compose stack
  command: docker compose up -d --force-recreate
  args:
    chdir: "{{ docker_compose_project_dir }}"
  async: 180
  poll: 10
