---
- name: Ensure host entries are in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
    state: present
    create: yes
    insertafter: EOF
  loop: "{{ hosts_entries }}"
  tags: [networking, etc_hosts]
